# fly.toml app configuration file generated for agentkernel-weathered-dew-4966 on 2026-05-21T22:44:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentkernel'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  BASE_URL = 'https://api.deepseek.com'
  DATA_DIR = '/tmp/.aicore'
  MODEL = 'deepseek-chat'
  PROTOCOL = 'openai'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
